import { Router, type IRouter } from "express";
import healthRouter from "./health";
import placesRouter from "./places";
import timelinesRouter from "./timelines";
import insightsRouter from "./insights";
import savedPlacesRouter from "./savedPlaces";
import savedInsightsRouter from "./savedInsights";
import savedJourneysRouter from "./savedJourneys";
import savedMapsRouter from "./savedMaps";
import chatRouter from "./chat";
import analyticsRouter from "./analytics";
import viralRouter from "./viral";
import plannerRouter from "./planner";
import capsuleRouter from "./capsule";
import forecastRouter from "./forecast";
import eventsRouter from "./events";
import cityRouter from "./city";
import reporterRouter from "./reporter";
import portfolioRouter from "./portfolio";
import alertsRouter from "./alerts";
import crowdRouter from "./crowd";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(placesRouter);
router.use(timelinesRouter);
router.use(insightsRouter);
router.use(savedPlacesRouter);
router.use(savedInsightsRouter);
router.use(savedJourneysRouter);
router.use(savedMapsRouter);
router.use(chatRouter);
router.use(analyticsRouter);
router.use(viralRouter);
router.use(plannerRouter);
router.use(capsuleRouter);
router.use(forecastRouter);
router.use(eventsRouter);
router.use(cityRouter);
router.use(reporterRouter);
router.use(portfolioRouter);
router.use(alertsRouter);
router.use(crowdRouter);
router.use(adminRouter);

export default router;
